server:
  port: 8080

spring:
  application:
    name: scrapper
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/scrapper
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: ${MIGRATIONS_ENABLED:false}
