server:
  port: 8080

spring:
  application:
    name: scrapper
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/scrapper
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: ${MIGRATIONS_ENABLED:false}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
  consumers:
    link-outbox:
      topic: gateway.link.outbox
      group-id: gateway-link-outbox-scrapper
    link-rule-outbox:
      topic: gateway.link-rule.outbox
      group-id: gateway-link-rule-outbox-scrapper
  producers:
    link-update:
      topic: scrapper.link.update
      partitions: 2
      replicas: 2

schedule:
  tasks:
    link:
      cron: '0 0 */6 * * *' # every 6 hours

feign:
  wildberries:
    link:
      batch-size: 50
    rule:
      batch-size: 100
    api:
      url: https://card.wb.ru
      dest: -5818883
      curr: rub