server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
  application:
    name: gateway
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/gateway
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: ${MIGRATIONS_ENABLED:false}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

kafka:
  bootstrap-servers: ${spring.kafka.bootstrap-servers}
  producers:
    link-outbox:
      topic: gateway.link.outbox
      partitions: 2
      replicas: 2
    link-rule-outbox:
      topic: gateway.link-rule.outbox
      partitions: 2
      replicas: 2
    link-update:
      topic: gateway.link.update
      partitions: 2
      replicas: 2
  consumers:
    link-update:
      topic: scrapper.link.update
      group-id: scrapper-link-update-gateway
      enable: true

schedule:
  tasks:
    link-outbox:
      cron: '0 * * * * *' # every minute
    link-rule-outbox:
      cron: '0 * * * * *' # every minute